name: Build

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v6
              with:
                  persist-credentials: false

            - name: Setup
              uses: allons-y/setup-action@v1

            - name: Run build
              run: yarn ci

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v6
              with:
                  persist-credentials: false

            - name: Setup
              uses: allons-y/setup-action@v1

            - name: Run lint
              run: yarn lint
