name: Release

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            id-token: write
        steps:
            - name: Check out code
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Setup Node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version-file: .nvmrc
                  cache: yarn

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build
              run: yarn build

            - name: Create release pull request or publish
              uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1
              with:
                  version: yarn version-packages
                  publish: yarn release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_CONFIG_PROVENANCE: "true"
